version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flapp-backend
    restart: always
    env_file:
      - ./.env
    networks:
      - flapp-network
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - DUMMY_API=${DUMMY_API:-https://dummyjson.com}
      - UDER_CREDENTIAL=${UDER_CREDENTIAL}
      - TRAELOYA_CREDENTIAL=${TRAELOYA_CREDENTIAL}
      - UDER_URL=${UDER_URL}
      - TRAELOYA_URL=${TRAELOYA_URL}

  frontend:
    build:
      context: ./frontend
    container_name: flapp-frontend
    restart: always
    networks:
      - flapp-network
    ports:
      - "3000:80"  # Mapea el puerto 3000 del host al puerto 80 del contenedor
    depends_on:
      - backend

networks:
  flapp-network:
    driver: bridge